---
- name: 
  user: Create projects users and home
    name: "{{ item.user }}"
    home: "{{ item.root }}"
    state: present
  with_items: "{{ django_projects }}"

- name: Make sure permissions are correct
  file:
    path: "{{ item.root }}"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0700"
    state: directory
  with_items: "{{ django_projects }}"
