---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- include_tasks: "common.yml"
- include_tasks: "python3.yml"
- include_tasks: "pip.yml"
