---
- name: python3 | Install epel release
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever
  when: "ansible_os_family == 'RedHat'"

- name: python3 | Install python 3 and pip
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ django_python3_packages }}"

- name: python3 | Install pip via setuptools for CentOS 6
  command: python3 /usr/lib/python3.4/site-packages/easy_install.py --upgrade pip
  changed_when: "'is already the active version' not in easy_install_result.stdout"
  register: easy_install_result
  when: "ansible_os_family + ansible_distribution_major_version == 'RedHat6'"
